-- DESPENSA NX - PUSH NOTIFICATIONS
-- Execute uma vez no SQL Editor do mesmo projeto Supabase.

create table if not exists public.lar_config (
  user_id uuid primary key references auth.users(id) on delete cascade,
  dias_alerta integer not null default 7 check (dias_alerta between 1 and 90),
  updated_at timestamptz not null default now()
);

alter table public.lar_config enable row level security;

drop policy if exists "lar_config_select_own" on public.lar_config;
create policy "lar_config_select_own" on public.lar_config for select to authenticated using (auth.uid() = user_id);

drop policy if exists "lar_config_insert_own" on public.lar_config;
create policy "lar_config_insert_own" on public.lar_config for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "lar_config_update_own" on public.lar_config;
create policy "lar_config_update_own" on public.lar_config for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

create table if not exists public.lar_push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists lar_push_subscriptions_user_idx on public.lar_push_subscriptions(user_id);

alter table public.lar_push_subscriptions enable row level security;

drop policy if exists "lar_push_select_own" on public.lar_push_subscriptions;
create policy "lar_push_select_own" on public.lar_push_subscriptions for select to authenticated using (auth.uid() = user_id);

drop policy if exists "lar_push_insert_own" on public.lar_push_subscriptions;
create policy "lar_push_insert_own" on public.lar_push_subscriptions for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "lar_push_update_own" on public.lar_push_subscriptions;
create policy "lar_push_update_own" on public.lar_push_subscriptions for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "lar_push_delete_own" on public.lar_push_subscriptions;
create policy "lar_push_delete_own" on public.lar_push_subscriptions for delete to authenticated using (auth.uid() = user_id);
