-- DESPENSA NX
-- Execute este arquivo uma única vez no SQL Editor do Supabase.
-- Ele NÃO altera a tabela "produtos" usada pelo Inventário NX.

create table if not exists public.lar_produtos (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  nome text not null,
  produto_base text,
  marca text,
  codigo_barras text,
  foto text,
  quantidade numeric(12,3) not null default 0,
  unidade_medida text not null default 'unidade',
  categoria text not null default 'Despensa',
  vencimento date,
  estoque_minimo numeric(12,3) not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists lar_produtos_user_id_idx on public.lar_produtos(user_id);
create index if not exists lar_produtos_produto_base_idx on public.lar_produtos(produto_base);
create index if not exists lar_produtos_vencimento_idx on public.lar_produtos(vencimento);

alter table public.lar_produtos enable row level security;

drop policy if exists "lar_produtos_select_own" on public.lar_produtos;
create policy "lar_produtos_select_own"
on public.lar_produtos for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "lar_produtos_insert_own" on public.lar_produtos;
create policy "lar_produtos_insert_own"
on public.lar_produtos for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "lar_produtos_update_own" on public.lar_produtos;
create policy "lar_produtos_update_own"
on public.lar_produtos for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "lar_produtos_delete_own" on public.lar_produtos;
create policy "lar_produtos_delete_own"
on public.lar_produtos for delete
to authenticated
using (auth.uid() = user_id);

insert into storage.buckets (id, name, public)
values ('lar-produtos', 'lar-produtos', true)
on conflict (id) do update set public = true;

drop policy if exists "lar_produtos_storage_read" on storage.objects;
create policy "lar_produtos_storage_read"
on storage.objects for select
to public
using (bucket_id = 'lar-produtos');

drop policy if exists "lar_produtos_storage_insert" on storage.objects;
create policy "lar_produtos_storage_insert"
on storage.objects for insert
to authenticated
with check (bucket_id = 'lar-produtos');

drop policy if exists "lar_produtos_storage_update" on storage.objects;
create policy "lar_produtos_storage_update"
on storage.objects for update
to authenticated
using (bucket_id = 'lar-produtos')
with check (bucket_id = 'lar-produtos');

drop policy if exists "lar_produtos_storage_delete" on storage.objects;
create policy "lar_produtos_storage_delete"
on storage.objects for delete
to authenticated
using (bucket_id = 'lar-produtos');
